// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgynlQqg_5CbMy574Exh2uul0Gz7c38A',
    appId: '1:1077111675202:web:3f8f44e4ffc035ebc550db',
    messagingSenderId: '1077111675202',
    projectId: 'mundo-afd2b',
    authDomain: 'mundo-afd2b.firebaseapp.com',
    storageBucket: 'mundo-afd2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xhEtDKuJvtamXi3JWX_oY11-FRQ5adk',
    appId: '1:1077111675202:android:a417932a937ff2a0c550db',
    messagingSenderId: '1077111675202',
    projectId: 'mundo-afd2b',
    storageBucket: 'mundo-afd2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa93DqO2nBP6fPkAFUQ_lEcM05VV8XN7A',
    appId: '1:1077111675202:ios:409f69ec398bdd25c550db',
    messagingSenderId: '1077111675202',
    projectId: 'mundo-afd2b',
    storageBucket: 'mundo-afd2b.appspot.com',
    iosClientId: '1077111675202-0bpjvuq8nou33g9v320iptp0jnhqscei.apps.googleusercontent.com',
    iosBundleId: 'com.example.imunus',
  );
}
